### ISSUE TITLE
website - first iteration for 2021 version

### ISSUE THREAD

**Issue by e-maud** [cohure/CHR-2021#3]
**Context**
https://www.computational-humanities-research.org/ 
Ideally it would be good to have a first version of the website ready at the same time the CFP is issued.

Q: How to differentiate the CHR generic website from the conference series (?)
https://chr2020.www.computational-humanities-research.org/ 
https://chr2021.www.computational-humanities-research.org/ ?

**Todos** (to be defined by communication team)
- [x] set up domains
- [x] move old website to other domain
- [x] init new website
- [ ] add cfp to new website

**Comment by fbkarsdorp** [comment]
First version is live at http://2021.computational-humanities-research.org/
